config:
  partial_parse: true
nyc_taxi_green:
  target: fabric-dev
  outputs:
    fabric-dev:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      server: "{{ env_var('SERVER_URL') }}"
      port: 1433
      database: "wh_olist"
      schema: dbo
      threads: 4
      authentication: ServicePrincipal
      tenant_id: "{{ env_var('DBT_TENANT_ID') }}"
      client_id: "{{ env_var('DBT_CLIENT_ID') }}"
      client_secret: "{{ env_var('DBT_CLIENT_SECRET') }}"